name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    runs-on: ubuntu-latest


3^3=3*3*3=27
#include <iostream>
using namespace std;
int main() 
{
int power;
float base, result = 1;
cin >> base >>power;
while (power != 0) {
    result *= base;
    power--;
}
cout << result;
return 0;
}



