

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test:
    runs-on: ubuntu-latest
    name: Docker Image CI

version: '3'
    
    
services:

  beersnob_database:
    container_name: beersnob_database
    hostname: beersnob_database
    image: postgres
    volumes:
      - ./volume:/var/lib/postgresql
    environment:
      - POSTGRES_DB=beersnobdb, beersnobdb_dev
      - POSTGRES_USER=mhuls
      - POSTGRES_PASSWORD=aStrongPassword
    ports:
      - 54321:5432
    restart: unless-stopped
    healthcheck:
      test: "exit 0"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

      # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

      # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
          echo Add other actions to build,
          echo test, and deploy your project.
